[versions]
kotlin = "2.0.21"
coroutines = "1.9.0"
androidxCore = "1.13.1"
appcompat = "1.7.0"
nordicBle = "1.3.1"
agp = "8.6.1"

[libraries]
# Kotlin + Coroutines
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# Nordic BLE
nordic-ble-core = { group = "no.nordicsemi.android.kotlin.ble", name = "core", version.ref = "nordicBle" }
nordic-ble-client = { group = "no.nordicsemi.android.kotlin.ble", name = "client", version.ref = "nordicBle" }
nordic-ble-scanner = { group = "no.nordicsemi.android.kotlin.ble", name = "scanner", version.ref = "nordicBle" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
